In [1]:
import pandas as pd
import numpy as np

In [2]:
# 데이터를 분석 하려면 데이터프레임 형태로 만들면 됨
# 행(인스턴스, 실제값), 열(속성, 특성)을 가지는 2차원이 되게 됨
# 파이썬에서는 데이터 분석시 사용하는 2차원을 다루기 위해서 클래스(부품)을 만들었음

In [3]:
dics = {"name" : ["홍길동","박길동","김길동","송길동"], "age":[10,20,30,40]}
df = pd.DataFrame(dics)
df

name  age
0  홍길동   10
1  박길동   20
2  김길동   30
3  송길동   40

In [52]:
# enumerate 연습
for i, item in enumerate(df['name'], 1):
    print(i, ": ", item, '님')

1 :  홍길동 님
2 :  박길동 님
3 :  김길동 님
4 :  송길동 님


In [25]:
name_values = ["홍길동","박길동","김길동","송길동"] # name, age = 요소 = feature(시리즈)
age_values = [10,20,30,40] #같은 타입의 값 = 벡터, 하나의 값 = 스칼라
df3 = pd.DataFrame({"name" : name_values, "age" : age_values})
df3

name  age
0  홍길동   10
1  박길동   20
2  김길동   30
3  송길동   40

In [4]:
# 인덱스가 자동 증가해서 붙어있는 부품 : 데이터프레임
df.index

RangeIndex(start=0, stop=4, step=1)

In [10]:
df_index = df.index.tolist() #리스트(비파괴), 인덱스만 목록을 가지고 오고 싶으면 list로 변경해서 사용
df_index

[0, 1, 2, 3]

In [5]:
type(df.index) #RangeIndex 부품, class

pandas.core.indexes.range.RangeIndex

In [6]:
df.name #시리즈는 작은 데이터프레임

0    홍길동
1    박길동
2    김길동
3    송길동
Name: name, dtype: object

In [28]:
# 시리즈를 데이터 프레임으로 변경할 수 있다.
df_name = df['name'].to_frame()
df_name

name
0  홍길동
1  박길동
2  김길동
3  송길동

In [7]:
df['name'] #동일

0    홍길동
1    박길동
2    김길동
3    송길동
Name: name, dtype: object

In [8]:
type(df['name']) #데이터 프레임 안에서 나머지 열은 시리즈, 리스트보다 훨씬 많은 데이터를 넣을 수 있음(class)

pandas.core.series.Series

In [11]:
# 데이터프레임은 Rangeindex, Series의 결합

In [12]:
# 시리즈는 인덱스와 array 객체의 결합

In [13]:
df['name'].index

RangeIndex(start=0, stop=4, step=1)

In [14]:
df_name_list = df['name'].index.tolist() #리스트로 convert
df_name_list

[0, 1, 2, 3]

In [15]:
df['name'].values #배열

array(['홍길동', '박길동', '김길동', '송길동'], dtype=object)

In [18]:
df_name_values = df['name'].values.tolist()
df_name_values

['홍길동', '박길동', '김길동', '송길동']

In [20]:
# 시리즈를 리스트로 변환, 인덱스가 생략한 형태의 리스트가 됨.
df_name_values2 = df['name'].values.tolist()
df_name_values2

['홍길동', '박길동', '김길동', '송길동']

## 데이터프레임을 만드는 방법
***
### dic 사용
### csv, excel 파일 읽어오기
### df에 values, column을 지정

In [24]:
df2 = pd.DataFrame(data = [['홍길동', 100],['김길동', 200]], columns=['name', 'age']) #데이타 & 컬럼 지정
df2

name  age
0  홍길동  100
1  김길동  200

In [29]:
type(df2.columns)

pandas.core.indexes.base.Index

In [30]:
df2.columns

Index(['name', 'age'], dtype='object')

In [31]:
df2.columns.tolist()

['name', 'age']

In [32]:
data = [100, 200, 300] #1차원인 리스트
sum(data)

600

In [33]:
max(data)

300

In [34]:
# ndarray : 다양한 차원의 데이터(배열)를 하나의 클래스로 다루기 위해서 만들어졌음
# n: 숫자
# d: dimesion, 차원
# array: 배열

In [36]:
arr1 = np.arange(15) #숫자 리스트를 어레이 객체로 만들어줌, 0 ~ 14까지의 연속된 값을 만들어주는 함수, 1차원
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
arr1_reshape = arr1.reshape(3, 5) #3행 5열, 원하는 차원(모양)으로 변환
arr1_reshape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [39]:
type(arr1_reshape) #ndarry : 차원, 배열 클래스

numpy.ndarray

In [41]:
# mask, 1차원
mask = np.zeros(5)
mask

array([0., 0., 0., 0., 0.])

In [42]:
mask2 = np.zeros((3, 4)) #2차원
mask2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
arr2 = np.array([
    [1, 2, 3], [4, 5, 6]
    ] , dtype=np.float64)  #2차원 어레이(행열) 만들기, 2차원 만들고 데이터 삽입
arr2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [44]:
arr3 = np.array([
    [7, 8, 9], [10, 11, 12]
    ] , dtype=np.float64)  #2차원 어레이(행열) 만들기, 2차원 만들고 데이터 삽입
arr3

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [45]:
# 행렬의 연산을 할 수 있음.(사칙연산 모두 가능)
arr2 + arr3

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [46]:
arr2 * arr3

array([[ 7., 16., 27.],
       [40., 55., 72.]])

In [48]:
arr2 - arr3

array([[-6., -6., -6.],
       [-6., -6., -6.]])

In [49]:
np.random.rand(20) #랜덤값 20개 생성

array([0.38504138, 0.53745233, 0.61776868, 0.38951712, 0.82474374,
       0.35945471, 0.10766536, 0.91282116, 0.27036729, 0.73684745,
       0.65845325, 0.52152129, 0.65296563, 0.37032515, 0.86773535,
       0.49465937, 0.64580368, 0.07368202, 0.19967941, 0.05517632])

In [50]:
np.random.randint(10) #랜덤 int값 10이하 가져오기

5